const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs=require('node:fs');
const baseURL=process.env.READLINGO_BASE_URL || 'http://127.0.0.1:8765';
const demo=process.env.READLINGO_DEMO==='1';
fs.mkdirSync('artifacts',{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.READLINGO_BROWSER_CHANNEL || undefined,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
 const context=await browser.newContext({viewport:{width:1440,height:1100},permissions:['microphone']});
 const page=await context.newPage(); const errors=[]; const apiRequests=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',request=>{if(new URL(request.url()).pathname.startsWith('/api/')) apiRequests.push(request.url());});
 await page.goto(baseURL);
 await page.locator('.word').first().waitFor();
 await page.getByRole('button',{name:'Consultar morning',exact:true}).click();
 assert.match(await page.locator('#word-meaning').innerText(),/mañana/);
 await page.locator('#word-save').click();
 await page.locator('#nav-review').click();
 await page.getByRole('button',{name:'Mostrar significado',exact:true}).click();
 await page.getByRole('button',{name:/Lo recordé/}).click();
 assert.match(await page.locator('#review-card').innerText(),/No tienes palabras/);
 await page.locator('#nav-reader').click();
 await page.locator('#next').click();
 await page.reload();
 assert.match(await page.locator('#paragraph-label').innerText(),/2 DE 3/);
 await page.evaluate(()=>selectWord('morning'));
 assert.equal(await page.locator('#word-source').innerText(),'Glosario local curado');
 await page.locator('#nav-vocab').click();
 assert.match(await page.locator('#vocab-list').innerText(),/Glosario local curado/);
 await page.locator('#nav-reader').click();
 await page.locator('#file-input').setInputFiles({name:'Lectura.txt',mimeType:'text/plain',buffer:Buffer.from('A fresh morning.\n\nA new garden.')});
 await page.waitForFunction(()=>document.getElementById('book-title').textContent==='Lectura');
 assert.match(await page.locator('#passage').innerText(),/fresh morning/);
 if(demo){
  assert.equal(await page.locator('html').getAttribute('data-runtime'),'demo');
  const intactBook=await page.evaluate(()=>localStorage.getItem('readlingo.v1'));
  await page.locator('#file-input').setInputFiles({name:'Unsupported.epub',mimeType:'application/epub+zip',buffer:Buffer.from('not an EPUB')});
  await page.waitForFunction(()=>/EPUB/.test(document.getElementById('status').textContent));
  assert.equal(await page.evaluate(()=>localStorage.getItem('readlingo.v1')),intactBook);
  await page.locator('#file-input').setInputFiles({name:'Unsafe.txt',mimeType:'text/plain',buffer:Buffer.from('<script>window.readlingoInjected=true</script>\n\n<img src=x onerror="window.readlingoInjected=true"> A café morning.')});
  await page.waitForFunction(()=>document.getElementById('book-title').textContent==='Unsafe');
  assert.equal(await page.evaluate(()=>window.readlingoInjected),undefined);
  assert.equal(await page.locator('#passage script, #passage img').count(),0);
  await page.locator('#next').click();
  assert.match(await page.locator('#passage').innerText(),/café morning/);
  await page.locator('.shelf-book').filter({has:page.locator('strong',{hasText:/^Lectura$/})}).click();
 }
 const beforeBackup=await page.evaluate(()=>JSON.parse(localStorage.getItem('readlingo.v1')));
 const downloadPromise=page.waitForEvent('download');
 await page.locator('#export-data').click();
 const download=await downloadPromise;
 const backup=fs.readFileSync(await download.path(),'utf8');
 assert.deepEqual(JSON.parse(backup).vocab,beforeBackup.vocab);
 page.on('dialog',dialog=>dialog.accept());
 await page.locator('#reset-data').click();
 assert.equal(await page.locator('#vocab-count').innerText(),'0');
 await page.locator('#restore-input').setInputFiles({name:'respaldo.json',mimeType:'application/json',buffer:Buffer.from(backup)});
 await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Respaldo restaurado'));
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('readlingo.v1'))),beforeBackup);
 await page.reload();
 assert.equal(await page.locator('#book-title').innerText(),'Lectura');
 await page.getByRole('button',{name:'Consultar morning',exact:true}).click();
 assert.equal(await page.locator('#word-source').innerText(),'Glosario local curado');
 const intact=await page.evaluate(()=>localStorage.getItem('readlingo.v1'));
 await page.locator('#restore-input').setInputFiles({name:'invalido.json',mimeType:'application/json',buffer:Buffer.from('{"version":2}')});
 await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('No se restauró'));
 assert.equal(await page.evaluate(()=>localStorage.getItem('readlingo.v1')),intact);
 assert.equal(await page.locator('#book-title').innerText(),'Lectura');
 await page.locator('#record').click();
 await page.waitForFunction(()=>document.getElementById('record').textContent.includes('Detener'));
 await page.waitForTimeout(1200);
 await page.locator('#record').click();
 await page.locator('#recording').waitFor({state:'visible'});
 const wav=await page.evaluate(async()=>{const buf=await audioToWav(recordBlob);const v=new DataView(buf);return {type:String.fromCharCode(...new Uint8Array(buf,0,4)),rate:v.getUint32(24,true),channels:v.getUint16(22,true),bits:v.getUint16(34,true),bytes:buf.byteLength}});
 assert.equal(wav.type,'RIFF');assert.equal(wav.rate,16000);assert.equal(wav.channels,1);assert.equal(wav.bits,16);
 assert.equal(await page.locator('#assessment-controls').isVisible(),false);
 await page.locator('.shelf-book').first().click();
 await page.locator('#prev').click();
 await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false);
 await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 if(demo) assert.deepEqual(apiRequests,[]);
 console.log(JSON.stringify({result:'PASS',baseURL,demo,flows:['dictionary','save vocabulary','review','navigation persistence','meaning source persistence','TXT import','backup download reset restore roundtrip','invalid backup preserves state','fake microphone recording','WAV conversion','unconfigured assessment hidden','mobile no overflow',...(demo?['EPUB rejection preserves state','UTF-8 TXT and HTML remain inert','no API requests']:[])],wav,errors,apiRequests}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
